//! macOS virtual keycodes (Carbon/CGEvent key space) for the keys a
//! `KeyChord` can name. Unknown keys are an explicit error — never guessed.

/// Canonical name → virtual keycode.
pub fn keycode(name: &str) -> Option<u16> {
    Some(match name {
        "a" => 0,
        "s" => 1,
        "d" => 2,
        "f" => 3,
        "h" => 4,
        "g" => 5,
        "z" => 6,
        "x" => 7,
        "c" => 8,
        "v" => 9,
        "b" => 11,
        "q" => 12,
        "w" => 13,
        "e" => 14,
        "r" => 15,
        "y" => 16,
        "t" => 17,
        "1" => 18,
        "2" => 19,
        "3" => 20,
        "4" => 21,
        "6" => 22,
        "5" => 23,
        "=" | "equal" => 24,
        "9" => 25,
        "7" => 26,
        "-" | "minus" => 27,
        "8" => 28,
        "0" => 29,
        "]" => 30,
        "o" => 31,
        "u" => 32,
        "[" => 33,
        "i" => 34,
        "p" => 35,
        "return" | "enter" => 36,
        "l" => 37,
        "j" => 38,
        "'" | "quote" => 39,
        "k" => 40,
        ";" | "semicolon" => 41,
        "\\" | "backslash" => 42,
        "," | "comma" => 43,
        "/" | "slash" => 44,
        "n" => 45,
        "m" => 46,
        "." | "period" => 47,
        "tab" => 48,
        "space" => 49,
        "`" | "backtick" => 50,
        "delete" | "backspace" => 51,
        "escape" | "esc" => 53,
        "f17" => 64,
        "f18" => 79,
        "f19" => 80,
        "f20" => 90,
        "f5" => 96,
        "f6" => 97,
        "f7" => 98,
        "f3" => 99,
        "f8" => 100,
        "f9" => 101,
        "f11" => 103,
        "f10" => 109,
        "f12" => 111,
        "f4" => 118,
        "home" => 115,
        "page_up" | "pageup" => 116,
        "forward_delete" | "del" => 117,
        "end" => 119,
        "f2" => 120,
        "page_down" | "pagedown" => 121,
        "f1" => 122,
        "left" => 123,
        "right" => 124,
        "down" => 125,
        "up" => 126,
        _ => return None,
    })
}

/// Modifier name → CGEventFlags bit.
pub fn modifier_flag(name: &str) -> Option<u64> {
    Some(match name {
        "shift" => crate::ffi::K_CG_FLAG_SHIFT,
        "ctrl" | "control" => crate::ffi::K_CG_FLAG_CONTROL,
        "alt" | "option" | "opt" => crate::ffi::K_CG_FLAG_ALT,
        "cmd" | "command" | "meta" => crate::ffi::K_CG_FLAG_CMD,
        _ => return None,
    })
}
